<<<<<<< HEAD
﻿spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201 
spring:
  profiles: dev
  application: 
    name: mocroserveicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka/   
---
server: 
  port: 8202 
spring:
  profiles: test
  application: 
    name: mocroserveicecloud-config-client
eureka: 
  client: 
    service-url: 
=======
﻿spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201 
spring:
  profiles: dev
  application: 
    name: mocroserveicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka-dev.com:7001/eureka/   
---
server: 
  port: 8202 
spring:
  profiles: test
  application: 
    name: mocroserveicecloud-config-client
eureka: 
  client: 
    service-url: 
>>>>>>> 79b2450c0af45c49344ebe1615c9eb8a4c7b8363
      defaultZone: http://eureka-test.com:7001/eureka/