spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml          #mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities      #所有的entity别名类所在的包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       #mapper映射文件

spring:
  profiles: dev
  application:
    name: mocroservicecloud-dept                               #这个名字就是对外暴露的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                 #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB03                 #数据库名称
    username: root
    password: tiger
    dbcp2:
      min-idle: 5                                               #数据库最小连接池数5
      initial-size: 5                                           #初始化连接数
      max-total: 5                                              #最大连接数
      max-wait-millis: 200                                      #等待连接获取的最大超时时间
      
      
eureka:                              #将服务端入驻到eureka中  告诉  入驻到eureka的位置是在哪
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: mocroservicecloud-dept8001    #更换eureka中显示的名字
    prefer-ip-address: true                       #显示ip地址

info:
  app.name: atguigu-mocroservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.verson: $project.version$   

---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml          #mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities      #所有的entity别名类所在的包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       #mapper映射文件

spring:
  profiles: test
  application:
    name: mocroservicecloud-dept                               #这个名字就是对外暴露的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                 #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02                 #数据库名称
    username: root
    password: tiger
    dbcp2:
      min-idle: 5                                               #数据库最小连接池数5
      initial-size: 5                                           #初始化连接数
      max-total: 5                                              #最大连接数
      max-wait-millis: 200                                      #等待连接获取的最大超时时间
      
      
eureka:                              #将服务端入驻到eureka中  告诉  入驻到eureka的位置是在哪
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: mocroservicecloud-dept8001    #更换eureka中显示的名字
    prefer-ip-address: true                       #显示ip地址

info:
  app.name: atguigu-mocroservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.verson: $project.version$   